apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbm
  labels:
    app: tbm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tbm # Match the same label as in template.labels
  template:
    metadata:
      labels:
        app: tbm
    spec:
      containers:
        - name: tbm
          image: grapetruedocker/tbm:1.0.0
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/tbm
          ports:
            - containerPort: 8444
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tbm
spec:
  selector:
    app: tbm
  ports:
    - protocol: TCP
      port: 8444
      targetPort: 8444
  type: LoadBalancer
